# Test generated by RoostGPT for test Testing12345 using AI Type Open AI and AI Model gpt-4


# RoostTestHash=a16706fdab

config:
  target: "{{ $processEnvironment.API_HOST }}"
  phases:
    - duration: 60
      arrivalRate: 10
  plugins:
    expect: {}
  payload:
    path: "disputeTransaction_post_others.csv"
    fields:
      - "customerId"
      - "emailId"
      - "transactionsData"
    skipHeader: true
  environments:
    dev:
      target: "http://dev.example.com"
    prod:
      target: "http://prod.example.com"

scenarios:
  - name: "Testing API failure responses"
    flow:
      - log: "Sending a request with invalid authorization token"
        post:
          url: "/disputeTransaction"
          headers:
            koreUserId: "bhhavvya"
            botId: "invalid_bot_id"
            accountId: "invalid_account_id"
            Authorization: "invalid_token"
          json:
            customerId: "{{ customerId }}"
            emailId: "{{ emailId }}"
            transactionsData: "{{ transactionsData }}"
          expect:
            - statusCode: 401
            - hasProperty: "err"
            - equals: 
              - "err.message"
              - "Error: Authorisation failed."
      
      - think: 1

      - log: "Sending a request to an invalid URL"
        post:
          url: "/invalid_url"
          headers:
            koreUserId: "bhhavvya"
            botId: "valid_bot_id"
            accountId: "valid_account_id"
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
          json:
            customerId: "{{ customerId }}"
            emailId: "{{ emailId }}"
            transactionsData: "{{ transactionsData }}"
          expect:
            - statusCode: 404
            - hasProperty: "err"
            - equals: 
              - "err.message"
              - "Error: Not Found"
